import { Metadata } from "next";
import { cache } from "react";
import { getAuditByPublicId } from "@/lib/db/repositories";
import PublicReportClient from "./PublicReportClient";
import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";

type Props = { params: Promise<{ publicId: string }> };

// Deduplicate DB calls within the same request using React cache
const fetchReport = cache(async (publicId: string) => {
  return getAuditByPublicId(publicId);
});

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { publicId } = await params;
  try {
    const row = await fetchReport(publicId);
    const monthlySavings = Number(row.total_monthly_savings).toFixed(2);
    const annualSavings = Number(row.total_annual_savings).toFixed(2);
    const title = `Lucent Audit — Save $${annualSavings}/yr`;
    const description = `Potential savings of $${monthlySavings}/mo ($${annualSavings}/yr) for a team of ${row.team_size}. Generated by Lucent.`;
    return {
      title,
      description,
      openGraph: { title, description, type: "website" },
      twitter: { card: "summary_large_image", title, description },
    };
  } catch {
    return {
      title: "Lucent Audit Snapshot",
      description: "View this share-safe SaaS audit report on Lucent.",
    };
  }
}

export default async function PublicReportPage({ params }: Props) {
  const { publicId } = await params;
  let data = null;
  let error = false;

  try {
    // fetchReport is cached — no second DB hit even though generateMetadata also calls it
    const row = await fetchReport(publicId);
    data = {
      publicId: row.public_id,
      totalMonthlySavings: Number(row.total_monthly_savings),
      totalAnnualSavings: Number(row.total_annual_savings),
    };
  } catch {
    error = true;
  }

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900">
      <SiteHeader />
      <main className="mx-auto w-full max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
        <PublicReportClient publicId={publicId} initialData={data} error={error} />
      </main>
      <SiteFooter />
    </div>
  );
}
